name: Check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/sbt-library-check.yml@master
    with:
      java-version: 17
      expect-tests: true