name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  publish:
    uses: wetransform/gha-workflows/.github/workflows/sbt-library-check.yml@master
    with:
      java-version: 17
      expect-tests: true
    secrets:
      WETF_ARTIFACTORY_USER:
        required: true
      WETF_ARTIFACTORY_PASSWORD:
        required: true
      SLACK_NOTIFICATIONS_BOT_TOKEN:
        required: true
